module.exports = {
  'team': "",
  'spawner': "",
  'lastAttack': Date.now(),
  'attackCooldown': 1500,
  'minionAttackDamage': 15,
  'creation': Date.now(),
  'changeDirectionTimmer': Date.now(),
  'changeDirectionCoolDown': 500,
  'CorrectDirectionChance':2,
  'radius': 10,
  'x': 0,
  'y': 0,
  'speed': 2,
  'randomx': 500,
  'randomy': 500,
  'dirX': "dirX",
  'dirY': "dirY",
  'target': {}
};